AWSTemplateFormatVersion: 2010-09-09
Description: Network template for Endpoint

Parameters:
  Project:
    Description: Project name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,20}$
  Component:
    Description: Name of the component
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,15}$
  Stage:
    Description: Stage name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$
  PrivateRouteTable:
    Description: Reference of the PrivateRouteTable from the SSM
    Type: AWS::SSM::Parameter::Value<String>
  PublicRouteTable:
    Description: Reference of the PublicRouteTable from the SSM
    Type: AWS::SSM::Parameter::Value<String>
  VpcId:
    Description: Reference of the VPC ID from the SSM
    Type: AWS::SSM::Parameter::Value<String>

Resources:
    S3GatewayEndpoint:
      Type: 'AWS::EC2::VPCEndpoint'
      Properties:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action: "*"
            Effect: Allow
            Resource: "*"
            Principal: "*"
        RouteTableIds:
          - !Ref PublicRouteTable
          - !Ref PrivateRouteTable
        ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
        VpcId: !Ref VpcId