AWSTemplateFormatVersion: 2010-09-09
Description: Network template for security groups

Parameters:
  Project:
    Description: Project name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,20}$
  Component:
    Description: Name of the component
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,15}$
  Stage:
    Description: Stage name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$
  VpcId:
    Description: Reference of the VpcId from the SSM
    Type: AWS::SSM::Parameter::Value<String>
  JumpHostAllowedCidrIpBlock:
    Description: CidrIp Block which will be have access open to JumpHost
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    Type: String
  JenkinsAllowedCidrIpBlock:
    Description: CidrIp Block which will be have access open to Jenkins
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    Type: String
  VpnConnection:
    Description: CidrIp Block which will be have access open to Jenkins
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    Type: String
  VerifyAppAllowedCidrIpBlock:
    Description: CidrIp Block which will be have access open to Verify App Server
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    Type: String
  ApplicationPort:
    Description: Port for API Application
    Type: String
  DatabasePort:
    Description: Port for Database
    Type: String
  MongodbPort:
    Description: Port for Database
    Type: String

Resources:
  JumpHostSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SecurityGroup for JumpHost
      GroupName: !Sub ${Project}-jumphost-sg
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: !Ref JumpHostAllowedCidrIpBlock
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Sub ${Project}-jumphost-sg

  JumpHostSecurityGroupParam:
      Type: AWS::SSM::Parameter
      Properties:
        Type: String
        Description: !Sub Stores ${Project} JumpHostSecurityGroup
        Tier: Standard
        Name: !Sub /jumphost-sg/sg-id
        Value: !Ref JumpHostSecurityGroup
        Tags:
          Name: !Sub ${Project}-jumphost-sg
      
  BatchSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SecurityGroup for Batch
      GroupName: !Sub batch-sg
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Sub batch-sg

  BatchSecurityGroupParam:
      Type: AWS::SSM::Parameter
      Properties:
        Type: String
        Description: !Sub Stores ${Project} BatchHostSecurityGroup
        Tier: Standard
        Name: !Sub /batch-sg/sg-id
        Value: !Ref BatchSecurityGroup
        Tags:
          Name: !Sub ${Project}-batch-sg
  

  AlbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SecurityGroup for Alb
      GroupName: !Sub ${Project}-alb-sg
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 0.0.0.0/0
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Sub ${Project}-alb-sg

  AlbSecurityGroupParam:
      Type: AWS::SSM::Parameter
      Properties:
        Type: String
        Description: !Sub Stores ${Project} AlbSecurityGroup
        Tier: Standard
        Name: !Sub /alb-sg/sg-id
        Value: !Ref AlbSecurityGroup
        Tags:
          Name: !Sub ${Project}-alb-sg

  ApplicationSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SecurityGroup for Verify App
      GroupName: !Sub ${Project}-application-sg
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: !Ref VpnConnection
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        SourceSecurityGroupId: !Ref JenkinsSecurityGroup
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        SourceSecurityGroupId: !Ref AlbSecurityGroup
      - IpProtocol: tcp
        FromPort: 443
        ToPort:  443
        SourceSecurityGroupId: !Ref AlbSecurityGroup
      - IpProtocol: tcp
        FromPort: 80
        ToPort:  80
        SourceSecurityGroupId: !Ref BatchSecurityGroup
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Sub ${Project}-application-sg

  ApplicationSecurityGroupParam:
      Type: AWS::SSM::Parameter
      Properties:
        Type: String
        Description: !Sub Stores ${Project} ApplicationSecurityGroup
        Tier: Standard
        Name: !Sub /application-sg/sg-id
        Value: !Ref ApplicationSecurityGroup
        Tags:
          Name: !Sub ${Project}-application-sg
 
  JenkinsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SecurityGroup for Jenkins
      GroupName: !Sub ${Project}-jenkins-sg
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: !Ref VerifyAppAllowedCidrIpBlock
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: !Ref VerifyAppAllowedCidrIpBlock
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Sub ${Project}-jenkins-sg

  JenkinsSecurityGroupParam:
      Type: AWS::SSM::Parameter
      Properties:
        Type: String
        Description: !Sub Stores ${Project} JenkinsSecurityGroup
        Tier: Standard
        Name: !Sub /jenkins-sg/sg-id
        Value: !Ref JenkinsSecurityGroup
        Tags:
          Name: !Sub ${Project}-jenkins-sg

  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SecurityGroup for Database
      GroupName: !Sub ${Project}-database-sg
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: !Ref DatabasePort
        ToPort: !Ref DatabasePort
        SourceSecurityGroupId: !Ref ApplicationSecurityGroup
      - IpProtocol: tcp
        FromPort: !Ref MongodbPort
        ToPort: !Ref MongodbPort
        SourceSecurityGroupId: !Ref ApplicationSecurityGroup
      - IpProtocol: tcp
        FromPort: !Ref DatabasePort
        ToPort: !Ref DatabasePort
        SourceSecurityGroupId: !Ref JumpHostSecurityGroup
      - IpProtocol: tcp
        FromPort: !Ref DatabasePort
        ToPort: !Ref DatabasePort
        SourceSecurityGroupId: !Ref BatchSecurityGroup
      - IpProtocol: tcp
        FromPort: !Ref MongodbPort
        ToPort: !Ref MongodbPort
        CidrIp: !Ref VpnConnection
      - IpProtocol: tcp
        FromPort: !Ref DatabasePort
        ToPort: !Ref DatabasePort
        CidrIp: !Ref VpnConnection
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Sub ${Project}-database-sg

  DatabaseSecurityGroupParam:
      Type: AWS::SSM::Parameter
      Properties:
        Type: String
        Description: !Sub Stores ${Project} DatabaseSecurityGroup
        Tier: Standard
        Name: !Sub /database-sg/sg-id
        Value: !Ref DatabaseSecurityGroup
        Tags:
          Name: !Sub ${Project}-database-sg
  ProcessingSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SecurityGroup for Processing EC2
      GroupName: !Sub processing-sg
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: !Ref JenkinsAllowedCidrIpBlock
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 192.168.252.0/23
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Sub processing-sg

  ProcessingSecurityGroupParam:
      Type: AWS::SSM::Parameter
      Properties:
        Type: String
        Description: !Sub Stores ProcessingHostSecurityGroup
        Tier: Standard
        Name: !Sub /processing-sg/sg-id
        Value: !Ref ProcessingSecurityGroup
        Tags:
          Name: !Sub processing-sg
Outputs:
  JumpHostSecurityGroupId:
    Description: The ID of JumpHost Security group
    Value: !Ref JumpHostSecurityGroup
  JumpHostSecurityGroupParamName:
    Description: The name of the SSM parameter where the Id of the JumpHost Security group is stored
    Value: !Ref JumpHostSecurityGroupParam
  AlbSecurityGroupId:
    Description: The ID of Alb Security group
    Value: !Ref AlbSecurityGroup
  AlbSecurityGroupParamName:
    Description: The name of the SSM parameter where the Id of the Alb Security group is stored
    Value: !Ref AlbSecurityGroupParam
  ApplicationSecurityGroupId:
    Description: The ID of Application Security group
    Value: !Ref ApplicationSecurityGroup
  ApplicationSecurityGroupParamName:
    Description: The name of the SSM parameter where the Id of the Application Security group is stored
    Value: !Ref ApplicationSecurityGroupParam
  DatabaseSecurityGroupId:
    Description: The ID of Database Security group
    Value: !Ref DatabaseSecurityGroup
  DatabaseSecurityGroupParamName:
    Description: The name of the SSM parameter where the Id of the Database Security group is stored
    Value: !Ref DatabaseSecurityGroupParam
