AWSTemplateFormatVersion: 2010-09-09
Description: Network template for VPC peering to VPN

Parameters:
  Project:
    Description: Project name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,20}$
  Component:
    Description: Name of the component
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,15}$
  Stage:
    Description: Stage name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$
  PrivateRouteTable:
    Description: Reference of the PrivateRouteTable from the SSM
    Type: AWS::SSM::Parameter::Value<String>
  PublicRouteTable:
    Description: Reference of the PublicRouteTable from the SSM
    Type: AWS::SSM::Parameter::Value<String>
  VpcId:
    Description: Reference of the VPC ID from the SSM
    Type: AWS::SSM::Parameter::Value<String>
  VpcCidrBlock:
    Description: VpcCidrBlock
    Type: String
  PeerVPCId:
    Description: PeerVPCId
    Type: String

Resources:
  vpc:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: !Ref VpcCidrBlock
      EnableDnsSupport: false
      EnableDnsHostnames: false
      InstanceTenancy: default
  vpcPeeringConnection:
    Type: 'AWS::EC2::VPCPeeringConnection'
    Properties:
      VpcId: !Ref VpcId
      PeerVpcId: !Ref PeerVPCId
      PeerOwnerId: 971702284436
      Region: eu-west-1
  
  vpcPeeringConnectionParam:
      Type: AWS::SSM::Parameter
      Properties:
        Type: String
        Description: !Sub Stores ${Project} vpcPeeringConnection
        Tier: Standard
        Name: !Sub /${Project}/vpcPeeringConnection-id
        Value: !Ref vpcPeeringConnection
        Tags:
          Name: !Sub ${Project}-vpcPeeringConnection-to-vpn
Outputs:
  VPCId:
    Value: !Ref VpcId
  VPCPeeringConnectionId:
    Value: !Ref vpcPeeringConnection