AWSTemplateFormatVersion: 2010-09-09
Description: Template for Jenkins Server

Parameters:
  ImageId:
    Description: Id of the Ubuntu 20.04 AMI
    Type: String
    Default: ami-04505e74c0741db8d
  InstanceType:
    Description: Type of instance for Jenkins Server
    Type: String
    Default: t3.medium
  SecurityGroup:
    Description: Verify Security Group from the SSM
    Type: String
    Default: 'sg-029d8b01be2ae46dd'
  KeyPairName:
    Description: Key pair Name to auth Vm
    Type: String
    Default: 'bootcamp-keys'
  PrivateSubnetBId:
    Description: Private Subnet Id from the SSM
    Type: String
    Default: 'subnet-01b4abed72c4c02aa'
  

Conditions:
  UseKeyPair: !Not [!Equals [!Ref KeyPairName, '']]

Resources:
  VerifyAppServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      DisableApiTermination: false
      KeyName: !If
        - UseKeyPair
        - !Ref KeyPairName
        - !Ref AWS::NoValue
      InstanceType: !Ref  InstanceType
      SecurityGroupIds:
        - !Ref SecurityGroup
      SubnetId: !Ref PrivateSubnetBId
      Tags:
        - Key: Name
          Value: !Sub Jenkins - master
      UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            sudo apt update
            sudo apt upgrade -y --force-yes -qq
            sudo apt install openjdk-11-jre-headless
            wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
            sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
            sudo apt update
            sudo apt install jenkins -y
            sudo systemctl start jenkins
            sudo systemctl enable jenkins

            sudo apt install nginx -y
            sudo touch /etc/nginx/sites-available/jenkins
            sudo nano /etc/nginx/sites-available/jenkins
            #copy configuration
            sudo rm /etc/nginx/sites-enabled/default
            sudo ln -s /etc/nginx/sites-available/jenkins /etc/nginx/sites-enabled
            sudo service nginx restart


            #Setting up Jenkins
            #login to:
            http://ip_address_or_domain_name:8080
            #copy the password from
            sudo cat /var/lib/jenkins/secrets/initialAdminPassword
            #click the "Install suggested plugins" option

            #1. Add credentials manage credentials -> global
            #2. Add nodes
            #3. Add configurations for application & docker build

            sudo bash -c cat > /etc/nginx/sites-available/jenkins << 'EOF'
            server {
                  listen 80 default_server;
                  listen [::]:80 default_server;
                  server_name build-dev.beaconcure.com;
                  root /usr/share/nginx/html;
                  # Load configuration files for the default server block.
                  #include /etc/nginx/default.d/*.conf;
                  location / {
                      proxy_set_header        Host $host;
                      proxy_set_header        X-Real-IP $remote_addr;
                      proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;

                      # Fix the "It appears that your reverse proxy set up is broken" error.
                      proxy_pass          http://127.0.0.1:8080;
                      proxy_read_timeout  90;

                      proxy_redirect      http://127.0.0.1:8080 https://build-dev.beaconcure.com;
                  }
              }

              EOF


